'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state=null,token='',busy=false,lastRefresh=0,built=false,lastConfig='',eventsSignature='';
const labels={Rotate_Start:'R轴启动',X_Move_Start:'X轴启动',Y_Move_Start:'Y轴启动',Z_Camera_Move_Start:'检测Z启动',Z_Scan_Move_Start:'扫码Z启动',Z_Grab_Move_Start:'抓取Z启动',PC_System_Ready:'PC系统就绪',PC_Start_Cmd:'PC启动命令',Soft_Stop_Cmd:'软停机命令',System_Reset_Cmd:'系统复位命令',Buzzer_Mute:'蜂鸣器消音',PC_Heartbeat_Resp:'PC心跳应答',Flip_Target_Face:'翻面目标面',Flip_Sorting:'翻面 / 放回命令',Sorting_Cmd:'公共取放料命令',Grab_ID:'抓手选择编号',Retry_Cmd:'异常处置命令',PC_Alarm_Code:'上位机报警码',Camera_Target_X:'X目标坐标',Camera_Target_Y:'Y目标坐标',Camera_Target_Z:'检测Z目标坐标',Scan_Target_Z:'扫码Z目标坐标',Grab_Target_Z:'抓取Z目标坐标',Rotate_Target_R:'R目标角度',Model_Number:'零件型号（REAL编码待确认）',Global_Target_Speed:'整体目标速度',PLC_Ready_State:'PLC就绪',PLC_Mode_Auto:'自动模式反馈',Start_Button:'启动按钮',Stop_Button:'停止按钮',Reset_Button:'复位按钮',EStop_Active:'物理急停',Stack_Light_Red:'三色灯红灯',Stack_Light_Green:'三色灯绿灯',Stack_Light_Yellow:'三色灯黄灯',Buzzer_State:'蜂鸣器状态',Start_Indicator:'启动指示灯',Stop_Indicator:'停止指示灯',Reset_Indicator:'复位指示灯',PLC_System_Fault:'PLC系统故障',PC_Communication_Alarm:'上位机通信报警',PC_Alarm:'上位机其他报警',PLC_Heartbeat_Req:'PLC心跳请求',Flip_Status:'翻面反馈',Flip_Unload_Status:'放回反馈',Sorting_Exec_Status:'公共取放料反馈',Alarm_Code:'报警码（位定义待提供）',Alarm_Level:'报警等级',Grab_Active_ID:'当前实际抓手',Machine_Current_Pos_X:'X实际位置',Machine_Current_Pos_Y:'Y实际位置',Machine_Current_Pos_Z:'检测Z实际位置',Machine_Current_Pos_R:'R实际角度',Scan_Current_Pos_Z:'扫码Z实际位置',Flip_Grap_Current_Pos_Z:'抓取Z实际位置',X_Actual_Speed:'X实际速度',Y_Actual_Speed:'Y实际速度'};
const axisPrefix={X:'X轴',Y:'Y轴',Z_Camera:'检测Z',Z_Scan:'扫码Z',Z_Grab:'抓取Z',Z_Grap:'抓取Z',Z_Flip:'翻面Z',R:'旋转R',Rotate:'旋转轴',Flip:'翻转轴'};
function label(p){if(labels[p.logicalName])return labels[p.logicalName];for(const [suffix,cn] of Object.entries({Positive_Limit:'正限位',Negative_Limit:'负限位',Home:'原点开关',Axis_Alarm:'报警',Pos_Confirmed:'到位反馈'})){if(p.logicalName.endsWith('_'+suffix))return (axisPrefix[p.logicalName.slice(0,-suffix.length-1)]||p.logicalName.slice(0,-suffix.length-1))+cn;}return p.description.split('；')[0]||p.logicalName;}
const domId=p=>p.id.replace(/[^a-zA-Z0-9]/g,'_');
const fmt=v=>v===null||v===undefined?'—':typeof v==='number'?Number.isInteger(v)?String(v):Number(v.toPrecision(7)).toString():String(v);
const actualPositionMbs=new Set([6064,6068,6076,6084,6088,6092]);
function positionFmt(v){if(typeof v!=='number'||!Number.isFinite(v))return fmt(v);const rounded=Number(v.toFixed(3));return (rounded===0&&v!==0?'≈':'')+(rounded===0?'0.000':rounded.toFixed(3));}
const clock=t=>t?new Date(t*1000).toLocaleTimeString('zh-CN',{hour12:false}):'尚无';
function fresh(){return !!state?.fresh&&performance.now()-lastRefresh<3000;}
function point(mb){return state.points.find(p=>p.mb===mb);}
function val(id){return fresh()&&state.values[id]?.quality==='Good'?state.values[id].value:null;}
function byMb(mb){return point(mb)?val(point(mb).id):null;}
function message(text,error=false){$('#toast').textContent=text;$('#toast').className='toast'+(error?' error':'');$('#toast').hidden=false;setTimeout(()=>$('#toast').hidden=true,6500);}
async function api(name,data={}){if(busy)return null;busy=true;controls();try{const r=await fetch('/api/'+name,{method:'POST',headers:{'Content-Type':'application/json','X-Console-Token':token},body:JSON.stringify(data)});const result=await r.json();if(!r.ok)throw Error(result.error+(result.errorCode!=null?' [原始码 '+result.errorCode+']':''));message(result.message||'操作已受理，请查看通信过程');if(result.operationId)$('#noteOperation').value=result.operationId;await refresh();return result;}catch(error){message(error.message,true);await refresh();return null;}finally{busy=false;controls();}}
function controls(){if(!state)return;$('#connect').disabled=busy||state.tcpConnected;$('#disconnect').disabled=busy||!state.tcpConnected;$('#heartbeat').disabled=busy||!fresh();$('#heartbeat').textContent=state.heartbeat.enabled?'停用心跳':'启用心跳';$$('[data-send],[data-axis],[data-clear],[data-command]').forEach(e=>e.disabled=busy||!fresh());$('#saveSettings').disabled=busy;$('#saveNote').disabled=busy;}
function stateText(p,v){if(v==null)return '无有效解释';if(p.type==='BOOL')return v===0?'0':v===1?'1':'异常BYTE '+v;
 if(p.logicalName.endsWith('Pos_Confirmed'))return ({0:'运动中',1:'到位',2:'超时'})[v]||'未知状态';
 if(p.logicalName==='Flip_Status')return ({0:'空闲',1:'执行中',2:'翻面完成',3:'翻面失败'})[v]||'未知状态';
 if(p.logicalName==='Flip_Unload_Status')return ({0:'空闲',1:'执行中',2:'放料完成',3:'失败'})[v]||'未知状态';
 if(p.logicalName==='Sorting_Exec_Status')return ({0:'空闲',1:'取料成功',2:'放料完成',3:'抓取失败 / 锁停'})[v]||'未知状态';
 if(p.logicalName==='Alarm_Level')return ({0:'无等级',1:'警告',2:'一般故障',3:'严重故障'})[v]||'未知等级';
 return '';
}
function signalHtml(p){const id=domId(p),pc=p.direction==='PC->PLC';return `<article class="signal" data-signal="${esc(p.id)}"><div class="signal-head"><div><h3>${esc(label(p))}</h3><div class="name">${esc(p.name)}</div></div><div class="value" id="v_${id}">—</div></div><div class="signal-info"><span class="address" id="addr_${id}"></span><span>${p.type} · ${p.size} BYTE</span><span id="quality_${id}"></span></div>${pc?`<div class="send-row"><label>待发送<input id="input_${id}" type="number" step="${p.type==='REAL'?'any':'1'}" ${p.type==='BOOL'?'min="0" max="1"':p.type==='INT'?'min="-32768" max="32767"':''} placeholder="${p.type==='BOOL'?'0 / 1':p.type==='REAL'?'原始小数值':'整数值'}"></label><button data-send="${esc(p.id)}">发送</button>${p.type==='BOOL'?`<button data-send="${esc(p.id)}" data-value="0">发 0</button><button data-send="${esc(p.id)}" data-value="1">发 1</button>`:''}</div><div class="last-send" id="sent_${id}">尚未发送 · 读回来自只读轮询</div>`:''}<details><summary>原寄存器 / 字节解释 / 原表注释</summary><div id="raw_${id}" class="raw"></div><p>${esc(p.description)}</p><p>${esc(p.sourceFile)} · 第 ${p.sourceRow} 行 · ${esc(p.address)}</p></details></article>`;}
function build(){if(built)return;built=true;$('#pcSignals').innerHTML=state.points.filter(p=>p.direction==='PC->PLC').map(signalHtml).join('');$('#plcSignals').innerHTML=state.points.filter(p=>p.direction==='PLC->PC').map(signalHtml).join('');
 $('#axisCards').innerHTML=Object.entries(state.axes).map(([key,a])=>`<article class="axis-card"><h3>${esc(a.label)}</h3><label>目标 REAL<input id="target_${key}" class="target" type="number" step="any" placeholder="填写目标；不预设坐标"></label><div id="axisval_${key}" class="axis-values"></div><button class="primary" data-axis="${key}">写目标并启动</button><button data-clear="${key}">清零启动</button><p id="axiscfg_${key}" class="hint"></p></article>`).join('');
 $('#axisSettings').innerHTML='<table><thead><tr><th>轴</th><th>最小值</th><th>最大值</th><th>容差</th><th>单位</th><th>安全高度</th></tr></thead><tbody>'+Object.entries(state.axes).map(([key,a])=>`<tr><td>${esc(a.label)}</td>${['minimum','maximum','tolerance','unit','safeHeight'].map(k=>`<td><input id="setting_${key}_${k}" type="${k==='unit'?'text':'number'}" step="any" placeholder="未配置"></td>`).join('')}</tr>`).join('')+'</tbody></table>';
 const mbs=[2012,2014,2016,2018,2020,2022,2006,2007,2008,2009];$('#manualCommands').innerHTML=mbs.map(mb=>{const p=point(mb);return `<article class="manual-command"><h3>${esc(label(p))}</h3><div class="name">${esc(p.name)}</div><p class="address">${p.address}</p><input id="cmd_${mb}" type="number" step="1" placeholder="${p.type==='BOOL'?'0 / 1':'填写原始整数'}"><button data-command="${mb}">发送此信号</button><p>${p.codes.length?p.codes.map(c=>esc(c.value+'='+c.label)).join('；'):esc(p.description)}</p>${mb===2018?'<p id="grabFeedback" class="hint"></p>':''}</article>`;}).join('');
 $('#host').value=state.config.host;$('#port').value=state.config.port;loadSettings();
}
function loadSettings(){if(!state)return;for(const k of ['unitId','pcBase','plcBase','feedbackFc','boolOrder','realWriteOrder','realReadOrder','byteWrite','sourceAddress','timeout','pollMs','actionTimeout'])$('#'+k).value=(state.config[k]??(k==='sourceAddress'?'':state.config.realOrder));for(const [axis,a] of Object.entries(state.config.axes))for(const k of ['minimum','maximum','tolerance','unit','safeHeight'])$('#setting_'+axis+'_'+k).value=a[k]??'';}
function render(){if(!state)return;build();const f=fresh(),hb=state.heartbeat;
 const metrics=[['TCP',state.tcpConnected?'已连通':'未连通',state.tcpConnected?'ok':'muted'],['有效Modbus应答',clock(state.lastModbusResponse),f?'ok':'muted'],['数据解释',!f?'最后一次数据':state.interpretationValid?'当前配置可解释':'部分字节异常',f&&state.interpretationValid?'ok':'warn'],['轮询耗时',state.pollMs==null?'—':state.pollMs+' ms',''],['超时次数',state.timeoutCount,''],['心跳变化 / 应答',hb.changes+' / '+hb.responses,hb.enabled&&hb.changes>0&&hb.state==='following'?'ok':hb.enabled?'warn':'muted']];
 $('#connectionMetrics').innerHTML=metrics.map(([l,v,c])=>`<div class="metric"><small>${l}</small><b class="${c}">${esc(v)}</b></div>`).join('');
 $('#interpretation').textContent=`当前解释配置 / 尚未现场校准：站号 ${state.config.unitId}，PC PDU ${state.config.pcBase}，PLC PDU ${state.config.plcBase}，反馈 FC0${state.config.feedbackFc}，BOOL ${state.config.boolOrder}，REAL发送 ${(state.config.realWriteOrder??state.config.realOrder).toUpperCase()}，REAL反馈 ${(state.config.realReadOrder??state.config.realOrder).toUpperCase()}（按现场字序解释，误差待验收）。本机网卡 ${state.config.sourceAddress||'自动识别实体网卡'}，实际TCP ${state.localEndpoint?state.localEndpoint.join(':'):'尚未连接'}。心跳 ${hb.enabled?'已启用':'未启用'} · ${({off:'未启用',waiting:'等待请求',following:'已同值应答',no_edge:'未观察到翻转',invalid:'请求字节无效',failed:'应答失败/已停用'})[hb.state]||hb.state} · 无变化超时 ${hb.timeouts}${hb.error?' · '+hb.error:''}`;
 $('#error').textContent=state.error?state.error+' [原始码 '+(state.errorCode??'未提供')+']':'';
 const stop=byMb(6020),fault=byMb(6035);$('#faultBanner').hidden=!(f&&(stop===1||fault===1||stop===null||fault===null));$('#faultBanner').textContent=stop===1?'物理急停触发：MB6020 = 1；动作启动暂停':fault===1?'PLC系统故障：MB6035 = 1；动作启动暂停':'急停/故障字节解释无效，请核对PLC及字节顺序；监视与原始报文仍可查看。';
 const hints=[];
 if(f){if(byMb(2009)===1)hints.push('系统复位MB2009持续为1：核对PLC复位逻辑，必要时由操作员手动发送0');if(byMb(2006)===0)hints.push('PC就绪MB2006为0：核对是否参与PLC单轴使能，不自动置1');for(const [axis,a] of Object.entries(state.axes)){const p=state.points.find(p=>p.id===a.startId);if(byMb(p.mb)===1)hints.push(a.label+'启动MB'+p.mb+'为1：观察动作或手动清零，不自动重发');}if(hb.enabled&&hb.state==='no_edge')hints.push('心跳请求未翻转：核对PLC握手逻辑');}
 $('#interlockHints').hidden=!hints.length;$('#interlockHints').textContent='现场联锁核对提示（未确认PLC内部阻挡原因）：'+hints.join('；');
 $('#logPath').textContent='本次日志位置：'+state.logPath;$('#configPath').textContent='本机配置：'+state.configPath;
 for(const p of state.points){const id=domId(p),v=state.values[p.id],s=state.sent[p.id],row=$(`[data-signal="${CSS.escape(p.id)}"]`);row.classList.toggle('stale',!f);row.classList.toggle('changed',f&&v?.changedAt&&Date.now()/1000-v.changedAt<1.5);$('#addr_'+id).textContent=p.address+' → PDU '+p.pdu;
  const rawValue=v?.value;const interpreted=f&&v?.quality==='Good';const danger=/Alarm|Fault|EStop/.test(p.logicalName);
  $('#v_'+id).innerHTML=(p.type==='BOOL'?`<i class="lamp ${!f?'stale':rawValue===1?(danger?'alarm':'on'):''}"></i>`:'')+`<span class="${!f?'muted':v?.quality!=='Good'?'warn':danger&&rawValue===1?'bad':''}">${esc(actualPositionMbs.has(p.mb)?positionFmt(rawValue):fmt(rawValue))}</span> <small>${esc(stateText(p,rawValue))}</small>`;
  $('#quality_'+id).textContent=!f?'最后一次数据 · '+(v?clock(v.receivedEpoch):'未读取'):v?.quality==='Good'?'当前数据 · '+clock(v.receivedEpoch):'解释异常 · '+(v?.quality||'尚未读取');
  $('#v_'+id).title=actualPositionMbs.has(p.mb)?'实际位置原值：'+String(rawValue)+'；主显示保留三位小数，≈表示微小非零残差':'';
  $('#raw_'+id).innerHTML=`${p.type==='REAL'?'当前字序解码原值：'+esc(String(rawValue??'—'))+'<br>':''}原寄存器：${esc(v?.rawHex||'尚未读取')} / 十进制 ${esc(v?.registers?.join(', ')||'—')}<br>${p.type==='BOOL'?'BOOL 按整个 BYTE 解释；原字节 '+esc(fmt(rawValue)):p.type==='INT'?'16位有符号整数':Object.entries(v?.realAlternatives||{}).map(([k,value])=>esc(k+' = '+fmt(value))).join('<br>')}`;
  if(s)$('#sent_'+id).textContent=`最后发送 ${fmt(s.value)} · ${s.at} | PLC写应答 ${s.writeResponded?'已收到':'未确认'} | 读回 ${fmt(s.readback)} · ${s.readbackMatched===true?'相符':s.readbackMatched===false?'不符':'未确认'}${s.error?' · '+s.error:''}`;
 }
 for(const [axis,a] of Object.entries(state.axes)){$('#axisval_'+axis).innerHTML=`当前实际 <b title="原始反馈 ${esc(String(val(a.actualId)??'—'))}">${esc(positionFmt(val(a.actualId)))}</b> · ${esc(a.config.unit||'单位未配置')}<br><small>实际位置显示三位小数；≈为接近零，原值见悬停或信号详情</small><br>目标读回 ${esc(fmt(val(a.targetId)))} · 启动字节 ${esc(fmt(val(a.startId)))}<br>本轴报警 <b class="${val(a.alarmId)===1?'bad':'muted'}">${esc(fmt(val(a.alarmId)))}</b><br>反馈码 ${esc(fmt(val(a.feedbackId)))} / ${esc(stateText(state.points.find(p=>p.id===a.feedbackId),val(a.feedbackId)))}<br><span class="address">目标 ${state.points.find(p=>p.id===a.targetId).address} · 启动 ${state.points.find(p=>p.id===a.startId).address}</span>`;
  $('#axiscfg_'+axis).textContent=`范围 ${a.config.minimum??'未配置'} .. ${a.config.maximum??'未配置'}；容差 ${a.config.tolerance??'未配置 / 不作误差验收'}；安全高度 ${a.config.safeHeight??'未配置'}`;
  const active=state.actions.some(r=>r.axis===axis&&['observing','pending'].includes(r.state));$(`[data-axis="${axis}"]`).disabled=busy||!f||active;
 }
 if($('#grabFeedback'))$('#grabFeedback').textContent='实际选用抓手 MB6062 = '+fmt(byMb(6062));
 $('#actionRecords').innerHTML=state.actions.slice(-12).reverse().map(a=>`<article class="action-record"><button data-locate="${esc(a.operationId)}">${esc(a.label)} · ${esc(({observing:'观察中',pending:'待确认',completed:a.reusedPosition?'已在目标位置':'PLC本次到位',failed:'失败',timeout:'超时',interrupted:'中断',cancelled:'已清零'})[a.state]||a.state)}</button> <span class="muted">operationId ${esc(a.operationId)}</span><p>${esc(a.reason||'')} · 目标 ${fmt(a.target)} / 实际 ${fmt(a.actual)} / 差值 ${fmt(a.delta)}</p><div class="conclusions"><span>① PLC已应答写请求：${a.writeResponded?'是':a.reusedPosition?'未发送（沿用位置）':'未确认'}</span><span>② 目标读回相符：${a.readbackMatched?'是':a.reusedPosition?'无需写目标':'未确认'}</span><span>③ PLC反馈本次完成：${a.reusedPosition?'当前位置满足目标':a.plcCompleted===true?'是':a.plcCompleted===false?'否':'待确认'}</span></div><small>启动写应答 ${a.startWriteResponded===true?'已收到':'未确认'} / 启动读回 ${a.startReadbackMatched===true?'相符':'未确认'} · PLC启动后运动中反馈 ${a.busySeen?'已观察':'未观察'} · 完成证据 ${esc(a.completionEvidence||'尚未观察到PLC本次1→0→1')} · 启动清零 ${a.reusedPosition?'启动未发送，无需清零':a.cleared?'已读回':'未确认'} · 坐标误差验收 ${a.coordinateAcceptance==null?'未配置/未测':a.coordinateAcceptance?'在配置容差内':'超出配置容差'}${a.clearError?' · 清零失败 '+esc(a.clearError):''} · 机械执行以现场备注为准</small></article>`).join('')||'<p class="hint">暂无动作。连接不会自动启动设备。</p>';
 controls();for(const [axis] of Object.entries(state.axes)){const active=state.actions.some(r=>r.axis===axis&&['observing','pending'].includes(r.state));$(`[data-axis="${axis}"]`).disabled=busy||!f||active;}
 filterSignals();renderEvents();
}
function filterSignals(){const q=$('#search').value.trim().toLowerCase();for(const p of state?.points||[])$(`[data-signal="${CSS.escape(p.id)}"]`).hidden=!!q&&!`${label(p)} ${p.name} ${p.address} ${p.description}`.toLowerCase().includes(q);}
function renderEvents(){if(!state)return;const filter=$('#eventFilter').value,id=$('#operationFilter').value.trim();const records=state.events.filter(e=>(!id||e.operationId===id||e.actionId===id)&&(filter==='all'||filter==='wire'&&['TX','RX','RX_INVALID'].includes(e.kind)||filter==='signals'&&e.kind==='SIGNAL'||filter==='errors'&&/ERROR|FAILED|TIMEOUT/.test(e.kind)||filter==='operations'&&!['TX','RX','SIGNAL'].includes(e.kind))).slice(-180).reverse();const signature=records.map(e=>e.id).join(',')+filter+id;if(signature===eventsSignature)return;eventsSignature=signature;
 const openIds=new Set($$('#events details[open]').map(e=>e.dataset.event));
 $('#events').innerHTML=records.map(e=>`<details class="event" data-event="${esc(e.id)}" ${openIds.has(e.id)?'open':''}><summary><time>${clock(e.epoch)}</time><b class="${/ERROR|FAILED|TIMEOUT/.test(e.kind)?'bad':''}">${esc(e.title)}</b> <span class="muted">${esc(e.kind)} ${e.function?'FC'+e.function.toString(16).toUpperCase().padStart(2,'0'):''} ${e.operationId?'· '+esc(e.operationId):''}</span></summary><pre>${esc(JSON.stringify(e,null,2))}</pre></details>`).join('')||'<p class="hint">暂无匹配记录。连接后可在“全部”或“原始TX/RX”查看读取报文。</p>';
}
async function refresh(){try{const r=await fetch('/api/state',{cache:'no-store',signal:AbortSignal.timeout(3000)});state=await r.json();lastRefresh=performance.now();render();}catch(e){if(state){state.fresh=false;state.tcpConnected=false;state.error='本机服务暂时失联：'+e.message;render();}}}
function inputValue(id,type){const raw=$(id).value.trim();if(!raw)throw Error('请填写明确的发送值');const value=Number(raw);if(!Number.isFinite(value))throw Error('请输入有限数值');if(type!=='REAL'&&!Number.isInteger(value))throw Error('BOOL/INT请输入整数');return value;}
$('#connect').addEventListener('click',()=>api('connect',{host:$('#host').value.trim(),port:Number($('#port').value)}));$('#disconnect').addEventListener('click',()=>api('disconnect'));
$('#heartbeat').addEventListener('click',()=>api('heartbeat',{enabled:!state.heartbeat.enabled}));
$('#showSettings').addEventListener('click',()=>{$('#settings').hidden=!$('#settings').hidden;if(!$('#settings').hidden)loadSettings();});
$('#saveSettings').addEventListener('click',()=>{try{const data={};for(const k of ['unitId','pcBase','plcBase','feedbackFc','timeout','pollMs','actionTimeout'])data[k]=Number($('#'+k).value);for(const k of ['boolOrder','realWriteOrder','realReadOrder','byteWrite','sourceAddress'])data[k]=$('#'+k).value;data.axes={};for(const axis of Object.keys(state.axes)){data.axes[axis]={};for(const k of ['minimum','maximum','tolerance','unit','safeHeight']){const raw=$('#setting_'+axis+'_'+k).value.trim();data.axes[axis][k]=k==='unit'?raw:raw===''?null:Number(raw);}}api('settings',data);}catch(e){message(e.message,true);}});
document.addEventListener('click',async event=>{const b=event.target.closest('button');if(!b||b.disabled)return;try{
 if(b.dataset.send){const p=state.points.find(p=>p.id===b.dataset.send);const value=b.dataset.value!==undefined?Number(b.dataset.value):inputValue('#input_'+domId(p),p.type);await api('write',{id:p.id,value});}
 if(b.dataset.axis){const axis=b.dataset.axis;await api('axis',{axis,target:inputValue('#target_'+axis,'REAL')});}
 if(b.dataset.clear)await api('clear',{axis:b.dataset.clear});
 if(b.dataset.command){const p=point(Number(b.dataset.command));await api('write',{id:p.id,value:inputValue('#cmd_'+p.mb,p.type)});}
 if(b.dataset.locate){$('#operationFilter').value=b.dataset.locate;$('#noteOperation').value=b.dataset.locate;$('#eventFilter').value='all';eventsSignature='';renderEvents();$('#timeline').scrollIntoView();}
 }catch(e){message(e.message,true);}});
$('#saveNote').addEventListener('click',async()=>{if(await api('note',{text:$('#note').value,operationId:$('#noteOperation').value.trim()}))$('#note').value='';});
$('#search').addEventListener('input',filterSignals);$('#eventFilter').addEventListener('change',()=>{eventsSignature='';renderEvents();});$('#operationFilter').addEventListener('input',()=>{eventsSignature='';renderEvents();});
(async()=>{try{const r=await fetch('/api/session');token=(await r.json()).token;await refresh();setInterval(refresh,700);}catch(e){message('工作台初始化失败：'+e.message,true);}})();
